definitions:
  api.Appserver:
    properties:
      id:
        type: string
      is_owner:
        type: boolean
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/appserver:
    get:
      consumes:
      - application/json
      description: Get a list of appservers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Appserver'
            type: array
      summary: List Appservers
      tags:
      - appserver
swagger: "2.0"
